image: gitpod/workspace-full-vnc
tasks:
  - init: |
        pyenv install 3.9.7
        pyenv global 3.9.7
        pip3 install ev3sim==2.2.2
    command: ev3sim
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
