image:
  file: .gitpod.Dockerfile
tasks:
  - command: ev3sim
    name: ev3sim
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
vscode:
  extensions:
    - ms-python.python
    - ms-pyright.pyright
    - eamodio.gitlens
